pipeline {

    agent any

    stages {

        stage('Build') {

            steps {

                echo 'Construyendo...'

            }

        }

        stage('Pasamos a producción') { // Asegúrate de usar ' rectas

            steps {

                echo 'Desplegando...'

            }

        }

    }

}
